name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: Borales/actions-yarn@master
      - name: Build application
        run: yarn build
