name: Lighthouse

on: [push]

jobs:
  static-dist-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Borales/actions-yarn@master
      - name: Build the application
        run: yarn build
      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./lighthouserc.json"
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: ".lighthouseci"
