name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: actions/yarn@master
      uses: Borales/actions-yarn@master
    - name: Install dependencies
      run: yarn
